import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { RegistrationProvider } from "@/contexts/RegistrationContext";
import { AuthProvider } from "@/hooks/useAuth";

// Configure Poppins to provide a CSS variable
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // It's best to include all needed weights
  variable: "--font-sans", // This is the key change
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Apply the variable to the <html> tag
    <html lang="en" className={poppins.variable}>
      <body>
        <AuthProvider>
          <RegistrationProvider>{children}</RegistrationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}